In [22]:
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np
import sympy as sp
sp.init_printing()
import ipywidgets as ipw

In [28]:
sigma_x = 1
eta = np.arange(0,1.1,0.1)
sigma_ij = np.zeros((len(eta),2,2))
sigma_ij[:,0,0] = sigma_x
sigma_ij[:,0,1] = eta[:] * sigma_x
sigma_ij

array([[[1. , 0. ],
        [0. , 0. ]],

       [[1. , 0.1],
        [0. , 0. ]],

       [[1. , 0.2],
        [0. , 0. ]],

       [[1. , 0.3],
        [0. , 0. ]],

       [[1. , 0.4],
        [0. , 0. ]],

       [[1. , 0.5],
        [0. , 0. ]],

       [[1. , 0.6],
        [0. , 0. ]],

       [[1. , 0.7],
        [0. , 0. ]],

       [[1. , 0.8],
        [0. , 0. ]],

       [[1. , 0.9],
        [0. , 0. ]],

       [[1. , 1. ],
        [0. , 0. ]]])

In [45]:
beta = np.arange(0,1.60,0.15) #beta in radians
R_beta = np.zeros((len(eta),2,2))
R_beta[:,0,0] = np.cos(beta[:])
R_beta[:,0,1] = - np.sin(beta[:])
R_beta[:,1,0] = np.sin(beta[:])
R_beta[:,1,1] = np.cos(beta[:])
R_beta

array([[[ 1.        , -0.        ],
        [ 0.        ,  1.        ]],

       [[ 0.98877108, -0.14943813],
        [ 0.14943813,  0.98877108]],

       [[ 0.95533649, -0.29552021],
        [ 0.29552021,  0.95533649]],

       [[ 0.9004471 , -0.43496553],
        [ 0.43496553,  0.9004471 ]],

       [[ 0.82533561, -0.56464247],
        [ 0.56464247,  0.82533561]],

       [[ 0.73168887, -0.68163876],
        [ 0.68163876,  0.73168887]],

       [[ 0.62160997, -0.78332691],
        [ 0.78332691,  0.62160997]],

       [[ 0.49757105, -0.86742323],
        [ 0.86742323,  0.49757105]],

       [[ 0.36235775, -0.93203909],
        [ 0.93203909,  0.36235775]],

       [[ 0.21900669, -0.97572336],
        [ 0.97572336,  0.21900669]],

       [[ 0.0707372 , -0.99749499],
        [ 0.99749499,  0.0707372 ]]])

In [52]:
bar_sigma_beta_kl = np.einsum('...ki,...ij,...jl -> ...kl', R_beta, sigma_ij[0], R_beta)
bar_sigma_beta_kl

array([[[ 1.        ,  0.        ],
        [ 0.        ,  0.        ]],

       [[ 0.97766824, -0.1477601 ],
        [ 0.1477601 , -0.02233176]],

       [[ 0.91266781, -0.28232124],
        [ 0.28232124, -0.08733219]],

       [[ 0.81080498, -0.39166345],
        [ 0.39166345, -0.18919502]],

       [[ 0.68117888, -0.46601954],
        [ 0.46601954, -0.31882112]],

       [[ 0.5353686 , -0.49874749],
        [ 0.49874749, -0.4646314 ]],

       [[ 0.38639895, -0.48692382],
        [ 0.48692382, -0.61360105]],

       [[ 0.24757695, -0.43160468],
        [ 0.43160468, -0.75242305]],

       [[ 0.13130314, -0.33773159],
        [ 0.33773159, -0.86869686]],

       [[ 0.04796393, -0.21368994],
        [ 0.21368994, -0.95203607]],

       [[ 0.00500375, -0.07056   ],
        [ 0.07056   , -0.99499625]]])

In [58]:
a = 1
K_I = np.sqrt(np.pi * a) * bar_sigma_beta_kl[:,0,0]
K_I

array([1.77245385, 1.73287184, 1.61766157, 1.43711442, 1.20735812,
       0.94891614, 0.68487431, 0.43881871, 0.23272876, 0.08501385,
       0.00886892])

In [60]:
K_II = np.sqrt(np.pi * a) * bar_sigma_beta_kl[:,0,1]
K_II

array([ 0.        , -0.26189796, -0.50040136, -0.6942054 , -0.82599813,
       -0.88400692, -0.86304999, -0.76499938, -0.59861366, -0.37875556,
       -0.12506435])